package com.dasher.util;

public class ShowMsg {
	
//	public static final String checkLogin="You are not logged in, please login first.";  //您尚未登录，请先登录。
//	public static final String addSuc="Information added successfully";  //添加成功
//	public static final String addFail="Information added unsuccessfully"; //添加失败
//	public static final String addRepeat="User name already exists. Please enter again";//用户名已存在
//	public static final String ShopaddRepeat="Business name already exists. Please enter again";//商家名称已存在
//	public static final String loginSuc="Login successful";  //登录成功
//	public static final String loginFail="Login failed";  //登录失败
//	public static final String userNameNull="User name does not exist";//用户名不存在
//	public static final String pwdErr="Password Error";//密码错误
//	public static final String findSuc="Information query is successful";//查询成功
//	public static final String findFail="Information query is unsuccessful";//查询失败
//	public static final String updateSuc="Information modify success";//修改成功
//	public static final String updateFail="Information modify fail";//修改失败
//	public static final String userNull="User is null, please input again";//用户名为空，请重新输入
//	public static final String pwdLength="Password cannot be empty and length is between 6 to 30";//密码不可为空且长度为6-30之间
//	public static final String delSuc="Information deleted successfully";//删除成功
//	public static final String delFail="Information deleted unsuccessfully";//删除失败
//	public static final String ParFail="Parameter is invalid";//无效的参数
//	public static final String FirstNameNull="FirstName is null";//FirstName为空
//	public static final String LastNameNull="LastNameNull is null";//LastNameNull为空
//	public static final String EmailNull = "Email is null";//邮箱地址为空
//	public static final String AddressNull = "Address is null";//地址为空
//	public static final String MobilePhoneNull = "Mobile phone is null";//手机号码为空
//	public static final String LonLatNull = "Latitude and longitude is empty"; //经纬度为空
//	public static final String statusErr = "The status of the format is not correct"; //status的格式不正确
//	public static final String emailErr="Email address format is not correct";//邮箱格式不正确
//	public static final String NoLogin = "The user is not login, please login again";//用户没有登录
//	public static final String mobilePhoneErr="Mobile phone number format is not correct, please enter again";//手机号码格式不正确
//	public static final String inputErr="You input format is not correct";//你输入的格式不正确
//	public static final String LogoNull = "The store logo is empty";//店铺logo为空
//	public static final String shopNull="Businessman named empty";//商家名为空
//	public static final String typeTabNull="Business type is empty tags";//商家类型标签为空
//	public static final String NoPermiss = "You do not have permission to do this";//您没有权限进行此操作
//	public static final String DishTypeNull="Category name is empty, please enter again";//分类名称为空，请重新输入
//	public static final String sortNumErr = "The sortNum of the format is not correct"; //sortNum的格式不正确
//	public static final String ShopDishTypeaddRepeat = "Category name already exists. Please enter again";//分类名称已存在,请重新输入
//	public static final String sortNumNull="sortNum is null";//sortNum为空
//	public static final String ShopDishNull = "Business name is empty";//商家菜品名称为空
//	public static final String typeErr = "The typeId of the format is not correct"; //类型的格式不正确！
	
	
	public static final String checkLogin="您尚未登录，请先登录！";  //You are not logged in, please login first.
	public static final String addSuc="添加成功！";  //Information added successfully
	public static final String addFail="添加失败！"; //Information added unsuccessfully
	public static final String addRepeat="该手机号已被注册！";//User name already exists. Please enter again
	public static final String ShopaddRepeat="商家名称已存在！";//Business name already exists. Please enter again
	public static final String loginSuc="登录成功！";  //Login successful
	public static final String loginFail="登录失败！";  //Login failed
	public static final String userNameNull="账号不存在！";//User name does not exist
	public static final String pwdErr="密码错误！";//Password Error
	public static final String findSuc="查询成功！";//Information query is successful
	public static final String findFail="查询失败！";//Information query is unsuccessful
	public static final String updateSuc="修改成功！";//Information modify success
	public static final String updateFail="修改失败！";//Information modify fail
	public static final String userNull="登陆账号为空，请重新输入！";//User is null, please input again
	public static final String pwdLength="密码不可为空且长度为6-30之间！";//Password cannot be empty and length is between 6 to 30
	public static final String delSuc="删除成功！";//Information deleted successfully
	public static final String delFail="删除失败！";//Information deleted unsuccessfully
	public static final String ParFail="无效的参数！";//Parameter is invalid
	public static final String FirstNameNull="FirstName为空！";//FirstName is null
	public static final String LastNameNull="LastNameNull为空！";//LastNameNull is null
	public static final String EmailNull = "邮箱地址为空！";//Email is null
	public static final String AddressNull = "地址为空！";//Address is null
	public static final String MobilePhoneNull = "手机号码为空！";//Mobile phone is null
	public static final String LonLatNull = "经纬度为空！"; //Latitude and longitude is empty
	public static final String statusErr = "status的格式不正确！"; //The status of the format is not correct
	public static final String emailErr="邮箱格式不正确！";//Email address format is not correct
	public static final String NoLogin = "用户没有登录！";//The user is not login, please login again
	public static final String mobilePhoneErr="手机号码格式不正确！";//Mobile phone number format is not correct, please enter again
	public static final String inputErr="你输入的格式不正确！";//You input format is not correct
	public static final String LogoNull = "店铺logo为空！";//The store logo is empty
	public static final String shopNull="商家名为空！";//Businessman named empty
	public static final String typeTabNull="商家类型标签为空！";//Business type is empty tags
	public static final String NoPermiss = "您没有权限进行此操作！";//You do not have permission to do this
	public static final String DishTypeNull="分类名称为空，请重新输入！";//Category name is empty, please enter again
	public static final String sortNumErr = "sortNum的格式不正确！"; //The sortNum of the format is not correct
	public static final String ShopDishTypeaddRepeat = "分类名称已存在,请重新输入！";//Category name already exists. Please enter again
	public static final String sortNumNull="sortNum为空！";//sortNum is null
	public static final String ShopDishNull = "商家菜品名称为空";//Business name is empty
	public static final String priceNull="菜品价格为空";//Food prices is empty
	public static final String typeIdNull="菜品类型为空";//Food type is empty
	public static final String chiliesNull="菜品味道为空";//Dishes taste is empty
	public static final String typeErr = "类型格式不正确！"; //The typeId of the format is not correct
	public static final String priceErr="菜品价格格式不正确！";//The price of the format is not correct
	public static final String imageUploadFail="图片上传失败！";//Image upload failure
	public static final String imageUploadSuc="图片上传成功！";//Photos uploaded successfully
	public static final String dishsMoneyNull="订餐费为空";//Order meals is empty
	public static final String carriageMoneyNull="运费为空";//The freight is empty
	public static final String taxesMoneyNull="税费为空";//Taxation is empty
	public static final String serviceMoneyNull="服务费为空";//The service fee is empty
	public static final String tipMoneyNull="小费为空";//A tip is empty
	public static final String menuCountNull="订单菜品数为空";//Order number is empty
	public static final String menuCountErr="订单菜品数格式错误";//Order number format error
	public static final String payTypeNull="支付方式为空";//Payment is empty
	public static final String payTypeErr="支付方式格式错误";//Invalid format of payment
	public static final String dishsMoneyErr="订餐费格式错误";//Invalid format of order meals
	public static final String carriageMoneyErr="运费格式错误";//Invalid format of freight
	public static final String taxesMoneyErr="税费格式错误";//Invalid format of taxes and fees
	public static final String serviceMoneyErr="服务费格式错误";//服务费格式错误
	public static final String tipMoneyErr="小费格式错误";//Invalid format of tip
	public static final String menuSuc="您已订餐成功";//You have been order success
	public static final String menuFail="对不起，您订餐失败，请重试！";//Sorry, your order failed, please try again!
	public static final String NoPermiss2 = "您尚未通过送餐人的审核，没有权限进行订单的配送！";//You have not yet through the room of audit, that there was no authority to order delivery!
	public static final String receiveSuc="接单成功，请及时完成订单的配送！";//Order is successful, please finish the order delivery!
	public static final String receiveFail="接单失败，请重试！";//Single failure, please try again!
	public static final String searchFail="无效的查询条件！";//Invalid query conditions
	public static final String nameNull = "菜品名称为空";//Name is empty
	public static final String menuDishSuc="新增订单成功";//New orders successful
	public static final String menuDiahFail="对不起，您新增订单失败，请重试！";//Sorry, your new orders failed, please try again!
	public static final String evalSuc="评价成功";//Evaluation of success
	public static final String evalFail="对不起，您的评价失败，请重试！";//Sorry, your evaluation of failure, please try again!
	public static final String evalNull="评价分数为空！";
	public static final String evalErr="评价分数类型错误";
	public static final String bankAccountNull="银行卡账号为空";
	public static final String bankTypeNull="银行卡类型为空";
	public static final String mealStartDateNull="开始吃饭时间为空";
	public static final String mealEndDateNull="吃饭结束时间为空";
	public static final String marketNull="超市名称为空！";
	public static final String marketaddRepeat="超市名称已存在！";
	public static final String unitNull="商品单位为空";
	public static final String typeNull="商品类型为空！";
	public static final String proNameNull="商品名为空！";
	public static final String contentNull="投诉内容为空，请重新输入！";
	public static final String handleSuc="投诉处理成功！";
	public static final String comResultNull="投诉结果为空！";
	public static final String comResultErr="投诉结果格式不正确！";
	public static final String returnMoneyErr="返还金额格式错误!";
	public static final String deductMoneyErr="扣除金额格式错误!";
	public static final String handleFail="投诉处理失败！";
	public static final String settleTypeNull="用户收支类型为空！";
	public static final String settleNumberTypeNull="账号类型为空";
	public static final String settleNumberNull="订单号或银行账号为空";
	public static final String settlePriceNull="收支金额为空";
	public static final String settlePriceErr="收支金额格式错误";
	public static final String phoneCodeErr="手机验证码错误！";
	public static final String phoneRepeat="该手机号已被绑定！";
	public static final String NoLocatInfo = "没有获取位置，请重试！";
	public static final String distanceNull="附近距离为空！";
	public static final String LonLatErr = "经纬度格式错误";
	public static final String distanceErr="附近距离格式错误";
	public static final float distance=1000;
	public static final String weekNull="日期为空";
	public static final String weekErr="日期格式错误";
	public static final String flagNull="flag 为空";
	public static final String flagErr="flag格式错误";
	public static final String addrepeat="该店铺营业时间已添加，不可重复！";
	public static final String checkIng="提交认证成功！";
	public static final String checkFail="提交认证失败！";
	public static final String checkEnd="认证通过";
	public static final String chkFail="认证失败！";
	public static final String chkBank="您尚未填写银行账户。";
}
